// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Counterparty struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Phone     string `json:"phone"`
	Note      string `json:"note"`
	Tags      string `json:"tags"`
	CreatedAt string `json:"created_at"`
}

type Offset struct {
	ID             string `json:"id"`
	CounterpartyID string `json:"counterparty_id"`
	AmountCents    int64  `json:"amount_cents"`
	Note           string `json:"note"`
	OccurredAt     string `json:"occurred_at"`
	CreatedAt      string `json:"created_at"`
}

type OffsetAllocation struct {
	ID          string `json:"id"`
	OffsetID    string `json:"offset_id"`
	TradeID     string `json:"trade_id"`
	AmountCents int64  `json:"amount_cents"`
	CreatedAt   string `json:"created_at"`
}

type Payment struct {
	ID          string `json:"id"`
	TradeID     string `json:"trade_id"`
	AmountCents int64  `json:"amount_cents"`
	Note        string `json:"note"`
	OccurredAt  string `json:"occurred_at"`
	CreatedAt   string `json:"created_at"`
}

type Trade struct {
	ID             string `json:"id"`
	CounterpartyID string `json:"counterparty_id"`
	Type           string `json:"type"`
	Direction      string `json:"direction"`
	TotalCents     int64  `json:"total_cents"`
	Note           string `json:"note"`
	CreatedAt      string `json:"created_at"`
}

type TradeItem struct {
	ID         string `json:"id"`
	TradeID    string `json:"trade_id"`
	Name       string `json:"name"`
	Qty        int64  `json:"qty"`
	PriceCents int64  `json:"price_cents"`
}
