// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: trade.sql

package db

import (
	"context"
)

const counterpartyExists = `-- name: CounterpartyExists :one
SELECT EXISTS(SELECT 1 FROM counterparties WHERE id = ?) AS counterparty_exists
`

func (q *Queries) CounterpartyExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, counterpartyExists, id)
	var counterparty_exists int64
	err := row.Scan(&counterparty_exists)
	return counterparty_exists, err
}

const createCounterparty = `-- name: CreateCounterparty :exec
INSERT INTO counterparties (id, name, phone, note, tags, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCounterpartyParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Phone     string `json:"phone"`
	Note      string `json:"note"`
	Tags      string `json:"tags"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateCounterparty(ctx context.Context, arg CreateCounterpartyParams) error {
	_, err := q.db.ExecContext(ctx, createCounterparty,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Note,
		arg.Tags,
		arg.CreatedAt,
	)
	return err
}

const createOffset = `-- name: CreateOffset :exec
INSERT INTO offsets (id, counterparty_id, amount_cents, note, occurred_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateOffsetParams struct {
	ID             string `json:"id"`
	CounterpartyID string `json:"counterparty_id"`
	AmountCents    int64  `json:"amount_cents"`
	Note           string `json:"note"`
	OccurredAt     string `json:"occurred_at"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) CreateOffset(ctx context.Context, arg CreateOffsetParams) error {
	_, err := q.db.ExecContext(ctx, createOffset,
		arg.ID,
		arg.CounterpartyID,
		arg.AmountCents,
		arg.Note,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	return err
}

const createOffsetAllocation = `-- name: CreateOffsetAllocation :exec
INSERT INTO offset_allocations (id, offset_id, trade_id, amount_cents, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateOffsetAllocationParams struct {
	ID          string `json:"id"`
	OffsetID    string `json:"offset_id"`
	TradeID     string `json:"trade_id"`
	AmountCents int64  `json:"amount_cents"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) CreateOffsetAllocation(ctx context.Context, arg CreateOffsetAllocationParams) error {
	_, err := q.db.ExecContext(ctx, createOffsetAllocation,
		arg.ID,
		arg.OffsetID,
		arg.TradeID,
		arg.AmountCents,
		arg.CreatedAt,
	)
	return err
}

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (id, trade_id, amount_cents, note, occurred_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePaymentParams struct {
	ID          string `json:"id"`
	TradeID     string `json:"trade_id"`
	AmountCents int64  `json:"amount_cents"`
	Note        string `json:"note"`
	OccurredAt  string `json:"occurred_at"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.TradeID,
		arg.AmountCents,
		arg.Note,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	return err
}

const createTrade = `-- name: CreateTrade :exec
INSERT INTO trades (id, counterparty_id, type, direction, total_cents, note, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTradeParams struct {
	ID             string `json:"id"`
	CounterpartyID string `json:"counterparty_id"`
	Type           string `json:"type"`
	Direction      string `json:"direction"`
	TotalCents     int64  `json:"total_cents"`
	Note           string `json:"note"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) error {
	_, err := q.db.ExecContext(ctx, createTrade,
		arg.ID,
		arg.CounterpartyID,
		arg.Type,
		arg.Direction,
		arg.TotalCents,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const createTradeItem = `-- name: CreateTradeItem :exec
INSERT INTO trade_items (id, trade_id, name, qty, price_cents)
VALUES (?, ?, ?, ?, ?)
`

type CreateTradeItemParams struct {
	ID         string `json:"id"`
	TradeID    string `json:"trade_id"`
	Name       string `json:"name"`
	Qty        int64  `json:"qty"`
	PriceCents int64  `json:"price_cents"`
}

func (q *Queries) CreateTradeItem(ctx context.Context, arg CreateTradeItemParams) error {
	_, err := q.db.ExecContext(ctx, createTradeItem,
		arg.ID,
		arg.TradeID,
		arg.Name,
		arg.Qty,
		arg.PriceCents,
	)
	return err
}

const getTrade = `-- name: GetTrade :one
SELECT id, counterparty_id, type, direction, total_cents, note, created_at
FROM trades
WHERE id = ?
`

func (q *Queries) GetTrade(ctx context.Context, id string) (Trade, error) {
	row := q.db.QueryRowContext(ctx, getTrade, id)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.CounterpartyID,
		&i.Type,
		&i.Direction,
		&i.TotalCents,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getTradeTotal = `-- name: GetTradeTotal :one
SELECT total_cents
FROM trades
WHERE id = ?
`

func (q *Queries) GetTradeTotal(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTradeTotal, id)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const listCounterparties = `-- name: ListCounterparties :many
SELECT id, name, phone, note, tags, created_at
FROM counterparties
ORDER BY created_at DESC
`

func (q *Queries) ListCounterparties(ctx context.Context) ([]Counterparty, error) {
	rows, err := q.db.QueryContext(ctx, listCounterparties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Counterparty
	for rows.Next() {
		var i Counterparty
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Note,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterpartyBalances = `-- name: ListCounterpartyBalances :many
SELECT
  t.counterparty_id,
  CAST(COALESCE(SUM(CASE
    WHEN t.direction = 'in' AND t.total_cents > COALESCE(p.paid_cents, 0)
    THEN t.total_cents - COALESCE(p.paid_cents, 0)
    ELSE 0
  END), 0) AS INTEGER) AS receivable_cents,
  CAST(COALESCE(SUM(CASE
    WHEN t.direction = 'out' AND t.total_cents > COALESCE(p.paid_cents, 0)
    THEN t.total_cents - COALESCE(p.paid_cents, 0)
    ELSE 0
  END), 0) AS INTEGER) AS payable_cents
FROM trades t
LEFT JOIN (
  SELECT trade_id, SUM(amount_cents) AS paid_cents
  FROM (
    SELECT trade_id, amount_cents FROM payments
    UNION ALL
    SELECT trade_id, amount_cents FROM offset_allocations
  ) settled
  GROUP BY trade_id
) p ON p.trade_id = t.id
GROUP BY t.counterparty_id
`

type ListCounterpartyBalancesRow struct {
	CounterpartyID  string `json:"counterparty_id"`
	ReceivableCents int64  `json:"receivable_cents"`
	PayableCents    int64  `json:"payable_cents"`
}

func (q *Queries) ListCounterpartyBalances(ctx context.Context) ([]ListCounterpartyBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCounterpartyBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounterpartyBalancesRow
	for rows.Next() {
		var i ListCounterpartyBalancesRow
		if err := rows.Scan(&i.CounterpartyID, &i.ReceivableCents, &i.PayableCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTrades = `-- name: ListRecentTrades :many
SELECT id, counterparty_id, type, direction, total_cents, note, created_at
FROM trades
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) ListRecentTrades(ctx context.Context) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyID,
			&i.Type,
			&i.Direction,
			&i.TotalCents,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineEntries = `-- name: ListTimelineEntries :many
WITH entries AS (
  SELECT 'trade' AS kind, t.id, t.id AS trade_id, t.total_cents AS amount_cents,
    CAST(t.type || CASE WHEN t.note = '' THEN '' ELSE ' ' || t.note END AS TEXT) AS note,
    t.created_at AS at, '' AS offset_id
  FROM trades t
  WHERE t.counterparty_id = ?1
  UNION ALL
  SELECT 'payment' AS kind, p.id, p.trade_id, p.amount_cents, p.note, p.occurred_at, '' AS offset_id
  FROM payments p
  JOIN trades t ON t.id = p.trade_id
  WHERE t.counterparty_id = ?1
  UNION ALL
  SELECT 'offset' AS kind, a.id, a.trade_id, a.amount_cents, o.note, o.occurred_at, o.id
  FROM offset_allocations a
  JOIN offsets o ON o.id = a.offset_id
  JOIN trades t ON t.id = a.trade_id
  WHERE t.counterparty_id = ?1
)
SELECT kind, id, trade_id, amount_cents, note, at, offset_id
FROM entries
ORDER BY at DESC, CASE kind WHEN 'payment' THEN 0 ELSE 1 END, id DESC
`

type ListTimelineEntriesRow struct {
	Kind        string `json:"kind"`
	ID          string `json:"id"`
	TradeID     string `json:"trade_id"`
	AmountCents int64  `json:"amount_cents"`
	Note        string `json:"note"`
	At          string `json:"at"`
	OffsetID    string `json:"offset_id"`
}

func (q *Queries) ListTimelineEntries(ctx context.Context, counterpartyID string) ([]ListTimelineEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineEntries, counterpartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimelineEntriesRow
	for rows.Next() {
		var i ListTimelineEntriesRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.TradeID,
			&i.AmountCents,
			&i.Note,
			&i.At,
			&i.OffsetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradeItems = `-- name: ListTradeItems :many
SELECT id, trade_id, name, qty, price_cents
FROM trade_items
WHERE trade_id = ?
ORDER BY rowid
`

func (q *Queries) ListTradeItems(ctx context.Context, tradeID string) ([]TradeItem, error) {
	rows, err := q.db.QueryContext(ctx, listTradeItems, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeItem
	for rows.Next() {
		var i TradeItem
		if err := rows.Scan(
			&i.ID,
			&i.TradeID,
			&i.Name,
			&i.Qty,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrades = `-- name: ListTrades :many
SELECT id, counterparty_id, type, direction, total_cents, note, created_at
FROM trades
ORDER BY created_at DESC
`

func (q *Queries) ListTrades(ctx context.Context) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listTrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyID,
			&i.Type,
			&i.Direction,
			&i.TotalCents,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradesByCounterparty = `-- name: ListTradesByCounterparty :many
SELECT id, counterparty_id, type, direction, total_cents, note, created_at
FROM trades
WHERE counterparty_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTradesByCounterparty(ctx context.Context, counterpartyID string) ([]Trade, error) {
	rows, err := q.db.QueryContext(ctx, listTradesByCounterparty, counterpartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.CounterpartyID,
			&i.Type,
			&i.Direction,
			&i.TotalCents,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overviewBalances = `-- name: OverviewBalances :one
SELECT
  CAST(COALESCE(SUM(CASE
    WHEN t.direction = 'in' AND t.total_cents > COALESCE(p.paid_cents, 0)
    THEN t.total_cents - COALESCE(p.paid_cents, 0)
    ELSE 0
  END), 0) AS INTEGER) AS receivable_cents,
  CAST(COALESCE(SUM(CASE
    WHEN t.direction = 'out' AND t.total_cents > COALESCE(p.paid_cents, 0)
    THEN t.total_cents - COALESCE(p.paid_cents, 0)
    ELSE 0
  END), 0) AS INTEGER) AS payable_cents
FROM trades t
LEFT JOIN (
  SELECT trade_id, SUM(amount_cents) AS paid_cents
  FROM (
    SELECT trade_id, amount_cents FROM payments
    UNION ALL
    SELECT trade_id, amount_cents FROM offset_allocations
  ) settled
  GROUP BY trade_id
) p ON p.trade_id = t.id
`

type OverviewBalancesRow struct {
	ReceivableCents int64 `json:"receivable_cents"`
	PayableCents    int64 `json:"payable_cents"`
}

func (q *Queries) OverviewBalances(ctx context.Context) (OverviewBalancesRow, error) {
	row := q.db.QueryRowContext(ctx, overviewBalances)
	var i OverviewBalancesRow
	err := row.Scan(&i.ReceivableCents, &i.PayableCents)
	return i, err
}

const settlementTotalByTrade = `-- name: SettlementTotalByTrade :one
SELECT CAST(COALESCE(SUM(amount_cents), 0) AS INTEGER) AS settled_cents
FROM (
  SELECT p.amount_cents FROM payments p WHERE p.trade_id = ?1
  UNION ALL
  SELECT a.amount_cents FROM offset_allocations a WHERE a.trade_id = ?1
) settled
`

func (q *Queries) SettlementTotalByTrade(ctx context.Context, tradeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, settlementTotalByTrade, tradeID)
	var settled_cents int64
	err := row.Scan(&settled_cents)
	return settled_cents, err
}
